package logic;

public enum MovResponse
{
    FROM_OUT_OF_BOUNDS,
    FROM_EMPTY,
    PLAYER_MISMATCH,
    TO_OUT_OF_BOUNDS,
    TO_NOT_EMPTY,
    NO_MOVES_LEFT,
    OUT_OF_REACH,
    DIDNT_MOVE,

    NO_ATTACKED_PIECE_IN_RANGE,
    ATK_OUT_OF_BOUNDS,
    LANDS_ON_NOT_EMPTY,

    OK,
}